version: 2
build:
  os: ubuntu-24.04
  tools:
    # For available versions, see:
    # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
    python: "3.14"  # Keep in sync with .github/workflows/checks.yml
  commands:
    - pip install tox
    - tox -e docs -- $READTHEDOCS_OUTPUT/html
